@extends('layouts.public')
@section('content')
<section class="corporate-hero"><div class="corporate-container"><p class="eyebrow">CONTACT</p><h1>{{ $form['title']??'Contact our team' }}</h1><p class="lead">{{ $form['intro']??'Please use the contact details below.' }}</p></div></section><div class="corporate-container corporate-detail">
@if(session('enquiry_sent'))<p class="notice" role="status">Thank you. Your enquiry has been received for review.</p>@endif
@if($errors->any())<div class="errors" role="alert"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($form)<form method="get" class="project-filters"><div><label for="type">Enquiry type</label><select id="type" name="type">@foreach($forms as $key=>$option)<option value="{{ $key }}" @selected($type===$key)>{{ $key }}</option>@endforeach</select></div>@foreach($filters as $key=>$value)@if($key!=='type')<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif @endforeach<button class="button ink">Choose form</button></form>
@if($project)<p>Regarding project: <strong>{{ $project['title'] }}</strong></p>@endif
<div class="contact-form"><form method="post" action="{{ route('contact.store') }}">@csrf<input type="hidden" name="type" value="{{ $type }}">@if($project)<input type="hidden" name="content_entry_id" value="{{ $project['id'] }}">@endif @foreach(['utm_source','utm_medium','utm_campaign','utm_content','utm_term','cta'] as $key)<input type="hidden" name="{{ $key }}" value="{{ $filters[$key]??'' }}">@endforeach<div class="form-grid">
@foreach(['name'=>'Your name','email'=>'Email address','phone'=>'Phone number','location'=>'Project / enquiry location'] as $key=>$label)<div><label for="{{ $key }}">{{ $label }}{{ $key!=='phone' ? ' *' : '' }}</label><input id="{{ $key }}" name="{{ $key }}" type="{{ $key==='email' ? 'email' : ($key==='phone' ? 'tel' : 'text') }}" value="{{ old($key) }}" @required($key!=='phone')></div>@endforeach
@foreach($form['fields'] as $key)<div><label for="details-{{ $key }}">{{ \App\Services\EnquiryForms::FIELDS[$key] }}{{ in_array($key,$form['required_fields']) ? ' *' : '' }}</label><input id="details-{{ $key }}" name="details[{{ $key }}]" maxlength="1000" value="{{ old('details.'.$key) }}" @required(in_array($key,$form['required_fields']))></div>@endforeach<div class="full"><label for="message">Your message *</label><textarea id="message" name="message" rows="5" minlength="10" maxlength="5000" required>{{ old('message') }}</textarea></div></div><div class="honey" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" tabindex="-1" autocomplete="off"></div><label class="consent"><input type="checkbox" name="consent" value="1" @checked(old('consent')) required> I agree that my details may be used to respond to this enquiry.</label><button class="button ink">Send project enquiry ↗</button></form></div>@endif
<section class="corporate-group"><h2>Contact details</h2>@if($content['contact']['phone'])<p><a href="tel:{{ preg_replace('/[^+0-9]/','',$content['contact']['phone']) }}">{{ $content['contact']['phone'] }}</a></p>@endif @if($content['contact']['email'])<p><a href="mailto:{{ $content['contact']['email'] }}">{{ $content['contact']['email'] }}</a></p>@endif @if($content['contact']['address'])<p>{{ $content['contact']['address'] }}</p>@endif @if($content['contact']['whatsapp'])<p><a href="https://wa.me/{{ $content['contact']['whatsapp'] }}">Talk on WhatsApp ↗</a></p>@endif</section></div>
@endsection
