@extends('layouts.admin')
@section('title', $entry->exists ? 'Edit project' : 'Add project')
@section('content')
<p class="eyebrow">PROJECTS & PROGRESS</p><h1>{{ $entry->exists ? $entry->title : 'Add a project' }}</h1><p><a href="{{ route('admin.projects.index') }}">← All projects</a></p>
@if($entry->exists && $entry->status!=='published')
<section role="status"><h2>These changes are not live yet</h2>
@if($entry->publishedRevision)<p>Visitors currently see: <strong>{{ $entry->publishedRevision->payload['title'] }}</strong>. Saving this form updates your draft only.</p>@else<p>This project has not been published. Saving this form creates a private draft.</p>@endif
<p>Save your changes, then use <a href="#project-publication">Review & publication</a>: Submit for review → Approve project → Publish project. Publication updates the website automatically.</p></section>
@endif
<form method="post" action="{{ $entry->exists ? route('admin.projects.update',$entry) : route('admin.projects.store') }}">@csrf @if($entry->exists) @method('PUT') @endif
<input type="hidden" name="version" value="{{ $revision?->version ?? 0 }}">
<section><h2>Project overview</h2><div class="form-grid">
<div><label for="title">Project name</label><input id="title" name="title" value="{{ old('title',$payload['title']??'') }}" required   maxlength="180"></div>
<div><label for="location">Site location / Address</label><input id="location" name="location" value="{{ old('location',$payload['location']??'') }}"    maxlength="255"></div>
<div><label for="city">City</label><input id="city" name="city" value="{{ old('city',$payload['city']??'') }}" required   maxlength="255"></div>
<div><label for="state">State</label><input id="state" name="state" value="{{ old('state',$payload['state']??'') }}"    maxlength="255"></div>
<div><label for="country">Country</label><input id="country" name="country" value="{{ old('country',$payload['country']??'') }}"    maxlength="255"></div>
<div><label for="project_area">Project area (include unit)</label><input id="project_area" name="project_area" value="{{ old('project_area',$payload['project_area']??'') }}"    maxlength="255"></div>
<div><label for="built_up_area">Built-up area (include unit)</label><input id="built_up_area" name="built_up_area" value="{{ old('built_up_area',$payload['built_up_area']??'') }}"    maxlength="255"></div>
<div><label for="client">Client / partner</label><input id="client" name="client" value="{{ old('client',$payload['client']??'') }}"    maxlength="255"></div>
<div><label for="project_value">Project value (include currency)</label><input id="project_value" name="project_value" value="{{ old('project_value',$payload['project_value']??'') }}"    maxlength="255"></div>

</div></section><section><h2>Status & dates</h2><div class="form-grid"><div><label for="status">Project status</label><select id="status" name="status">@foreach(\App\Services\ProjectContent::STATUSES as $option)<option @selected(old('status',$payload['status']??'')===$option)>{{ $option }}</option>@endforeach</select></div>
<div><label for="sector">Sector</label><select id="sector" name="sector">@foreach(\App\Services\ProjectContent::SECTORS as $option)<option @selected(old('sector',$payload['sector']??'')===$option)>{{ $option }}</option>@endforeach</select></div>
<div><label for="stage">Current construction stage</label><select id="stage" name="stage">@foreach(\App\Services\ProjectContent::STAGES as $option)<option @selected(old('stage',$payload['stage']??'')===$option)>{{ $option }}</option>@endforeach</select></div>
<div><label for="progress">Progress percentage</label><input type="number" id="progress" name="progress" min="0" max="100" value="{{ old('progress',$payload['progress']??0) }}" required></div>
<div><label for="start_date">Start date</label><input type="date" id="start_date" name="start_date" value="{{ old('start_date',$payload['start_date']??'') }}" ></div>

<div><label for="actual_completion">Actual completion</label><input type="date" id="actual_completion" name="actual_completion" value="{{ old('actual_completion',$payload['actual_completion']??'') }}" ></div>
</div></section><details class="editor-group" open><summary>Scope & project story</summary><label for="description">Project description</label><textarea id="description" name="description" rows="4" maxlength="15000">{{ old('description',$payload['description']??'') }}</textarea>
<label for="scope">Our scope of work</label><textarea id="scope" name="scope" rows="4" maxlength="15000">{{ old('scope',$payload['scope']??'') }}</textarea>
<label for="engineering">Engineering</label><textarea id="engineering" name="engineering" rows="4" maxlength="15000">{{ old('engineering',$payload['engineering']??'') }}</textarea>
<label for="construction">Construction</label><textarea id="construction" name="construction" rows="4" maxlength="15000">{{ old('construction',$payload['construction']??'') }}</textarea>
<label for="management">Project management</label><textarea id="management" name="management" rows="4" maxlength="15000">{{ old('management',$payload['management']??'') }}</textarea>
<label for="technical_highlights">Technical highlights</label><textarea id="technical_highlights" name="technical_highlights" rows="4" maxlength="15000">{{ old('technical_highlights',$payload['technical_highlights']??'') }}</textarea>
<label for="quality_safety">Quality & safety</label><textarea id="quality_safety" name="quality_safety" rows="4" maxlength="15000">{{ old('quality_safety',$payload['quality_safety']??'') }}</textarea>
<label for="outcome">Project outcome</label><textarea id="outcome" name="outcome" rows="4" maxlength="15000">{{ old('outcome',$payload['outcome']??'') }}</textarea>
</details><details class="editor-group" open data-repeater="gallery"><summary>Project gallery</summary><p class="muted">Add, remove or reorder items. Changes take effect after publication.</p><div data-rows>
@foreach(old('gallery',$payload['gallery']??[]) as $index=>$row)
<fieldset data-row><div class="form-grid"><div><label for="gallery-{{ $index }}-media_id">Image / video</label><select id="gallery-{{ $index }}-media_id" name="gallery[{{ $index }}][media_id]"><option value="">Select media</option>@foreach($media->filter(fn($asset)=>str_starts_with($asset->mime,'image/') || $asset->mime==='video/mp4') as $asset)<option value="{{ $asset->id }}" @selected(($row['media_id']??null)==$asset->id)>{{ $asset->title }}</option>@endforeach</select></div><div><label for="gallery-{{ $index }}-category">Category</label><select id="gallery-{{ $index }}-category" name="gallery[{{ $index }}][category]">@foreach(\App\Services\ProjectContent::GALLERY_CATEGORIES as $option)<option @selected(($row['category']??'')===$option)>{{ $option }}</option>@endforeach</select></div><div><label for="gallery-{{ $index }}-caption">Caption</label><input id="gallery-{{ $index }}-caption" name="gallery[{{ $index }}][caption]" type="text" value="{{ $row['caption']??'' }}" ></div><div><label for="gallery-{{ $index }}-date">Date taken</label><input id="gallery-{{ $index }}-date" name="gallery[{{ $index }}][date]" type="date" value="{{ $row['date']??'' }}" ></div><div><label for="gallery-{{ $index }}-location">Location</label><input id="gallery-{{ $index }}-location" name="gallery[{{ $index }}][location]" type="text" value="{{ $row['location']??'' }}" ></div><div><label for="gallery-{{ $index }}-alt">Alternative text</label><input id="gallery-{{ $index }}-alt" name="gallery[{{ $index }}][alt]" type="text" value="{{ $row['alt']??'' }}" ></div><div><label for="gallery-{{ $index }}-description">Description</label><textarea id="gallery-{{ $index }}-description" name="gallery[{{ $index }}][description]" rows="3">{{ $row['description']??'' }}</textarea></div><div><label for="gallery-{{ $index }}-stage">Associated stage</label><input id="gallery-{{ $index }}-stage" name="gallery[{{ $index }}][stage]" type="text" value="{{ $row['stage']??'' }}" ></div><div><label for="gallery-{{ $index }}-equipment_id">Associated equipment</label><select id="gallery-{{ $index }}-equipment_id" name="gallery[{{ $index }}][equipment_id]"><option value="">None</option>@foreach($equipment as $item)<option value="{{ $item['id'] }}" @selected(($row['equipment_id']??null)==$item['id'])>{{ $item['title'] }}</option>@endforeach</select></div><div><label for="gallery-{{ $index }}-visible">Publicly visible</label><select id="gallery-{{ $index }}-visible" name="gallery[{{ $index }}][visible]"><option value="1" @selected($row['visible']??true)>Yes</option><option value="0" @selected(isset($row['visible']) && !$row['visible'])>No</option></select></div></div><button type="button" class="quiet" data-move="up">Move up</button> <button type="button" class="quiet" data-move="down">Move down</button> <button type="button" class="quiet" data-remove>Remove item</button></fieldset>
@endforeach</div>
@php($row=[])<template><fieldset data-row><div class="form-grid"><div><label for="gallery-__INDEX__-media_id">Image / video</label><select id="gallery-__INDEX__-media_id" name="gallery[__INDEX__][media_id]"><option value="">Select media</option>@foreach($media->filter(fn($asset)=>str_starts_with($asset->mime,'image/') || $asset->mime==='video/mp4') as $asset)<option value="{{ $asset->id }}" @selected(($row['media_id']??null)==$asset->id)>{{ $asset->title }}</option>@endforeach</select></div><div><label for="gallery-__INDEX__-category">Category</label><select id="gallery-__INDEX__-category" name="gallery[__INDEX__][category]">@foreach(\App\Services\ProjectContent::GALLERY_CATEGORIES as $option)<option @selected(($row['category']??'')===$option)>{{ $option }}</option>@endforeach</select></div><div><label for="gallery-__INDEX__-caption">Caption</label><input id="gallery-__INDEX__-caption" name="gallery[__INDEX__][caption]" type="text" value="{{ $row['caption']??'' }}" ></div><div><label for="gallery-__INDEX__-date">Date taken</label><input id="gallery-__INDEX__-date" name="gallery[__INDEX__][date]" type="date" value="{{ $row['date']??'' }}" ></div><div><label for="gallery-__INDEX__-location">Location</label><input id="gallery-__INDEX__-location" name="gallery[__INDEX__][location]" type="text" value="{{ $row['location']??'' }}" ></div><div><label for="gallery-__INDEX__-alt">Alternative text</label><input id="gallery-__INDEX__-alt" name="gallery[__INDEX__][alt]" type="text" value="{{ $row['alt']??'' }}" ></div><div><label for="gallery-__INDEX__-description">Description</label><textarea id="gallery-__INDEX__-description" name="gallery[__INDEX__][description]" rows="3">{{ $row['description']??'' }}</textarea></div><div><label for="gallery-__INDEX__-stage">Associated stage</label><input id="gallery-__INDEX__-stage" name="gallery[__INDEX__][stage]" type="text" value="{{ $row['stage']??'' }}" ></div><div><label for="gallery-__INDEX__-equipment_id">Associated equipment</label><select id="gallery-__INDEX__-equipment_id" name="gallery[__INDEX__][equipment_id]"><option value="">None</option>@foreach($equipment as $item)<option value="{{ $item['id'] }}" @selected(($row['equipment_id']??null)==$item['id'])>{{ $item['title'] }}</option>@endforeach</select></div><div><label for="gallery-__INDEX__-visible">Publicly visible</label><select id="gallery-__INDEX__-visible" name="gallery[__INDEX__][visible]"><option value="1" @selected($row['visible']??true)>Yes</option><option value="0" @selected(isset($row['visible']) && !$row['visible'])>No</option></select></div></div><button type="button" class="quiet" data-move="up">Move up</button> <button type="button" class="quiet" data-move="down">Move down</button> <button type="button" class="quiet" data-remove>Remove item</button></fieldset></template><button type="button" data-add>Add item</button></details>
<details class="editor-group" open data-repeater="faqs"><summary>Project FAQs</summary><p class="muted">Add, remove or reorder items. Changes take effect after publication.</p><div data-rows>
@foreach(old('faqs',$payload['faqs']??[]) as $index=>$row)
<fieldset data-row><div class="form-grid"><div><label for="faqs-{{ $index }}-question">Question</label><input id="faqs-{{ $index }}-question" name="faqs[{{ $index }}][question]" type="text" value="{{ $row['question']??'' }}" ></div><div><label for="faqs-{{ $index }}-answer">Answer</label><textarea id="faqs-{{ $index }}-answer" name="faqs[{{ $index }}][answer]" rows="3">{{ $row['answer']??'' }}</textarea></div></div><button type="button" class="quiet" data-move="up">Move up</button> <button type="button" class="quiet" data-move="down">Move down</button> <button type="button" class="quiet" data-remove>Remove item</button></fieldset>
@endforeach</div>
@php($row=[])<template><fieldset data-row><div class="form-grid"><div><label for="faqs-__INDEX__-question">Question</label><input id="faqs-__INDEX__-question" name="faqs[__INDEX__][question]" type="text" value="{{ $row['question']??'' }}" ></div><div><label for="faqs-__INDEX__-answer">Answer</label><textarea id="faqs-__INDEX__-answer" name="faqs[__INDEX__][answer]" rows="3">{{ $row['answer']??'' }}</textarea></div></div><button type="button" class="quiet" data-move="up">Move up</button> <button type="button" class="quiet" data-move="down">Move down</button> <button type="button" class="quiet" data-remove>Remove item</button></fieldset></template><button type="button" data-add>Add item</button></details>
<section><h2>Publication options</h2><label for="client_approved">Client name approved for public display</label><select id="client_approved" name="client_approved"><option value="0" @selected(!old('client_approved',$payload['client_approved']??false))>No</option><option value="1" @selected(old('client_approved',$payload['client_approved']??false))>Yes</option></select>
<label for="value_approved">Project value approved for public display</label><select id="value_approved" name="value_approved"><option value="0" @selected(!old('value_approved',$payload['value_approved']??false))>No</option><option value="1" @selected(old('value_approved',$payload['value_approved']??false))>Yes</option></select>
<label for="featured">Feature this project</label><select id="featured" name="featured"><option value="0" @selected(!old('featured',$payload['featured']??false))>No</option><option value="1" @selected(old('featured',$payload['featured']??false))>Yes</option></select>
</section>
<section><h2>Verification & search</h2><label for="seo_title">SEO title</label><input id="seo_title" name="seo_title" value="{{ old('seo_title',$payload['seo_title']??'') }}"><label for="seo_description">SEO description</label><textarea id="seo_description" name="seo_description" rows="2">{{ old('seo_description',$payload['seo_description']??'') }}</textarea><label for="source_note">Source / approval reference (internal)</label><textarea id="source_note" name="source_note" rows="3">{{ old('source_note',$payload['source_note']??'') }}</textarea><input type="hidden" name="verified" value="0"><label><input type="checkbox" name="verified" value="1" @checked(old('verified',$payload['verified']??false))> These project facts are verified and approved for publication.</label><button>Save project draft</button></section></form>
@if($entry->exists)
@can('media.upload')
@can('media.manage')
<section id="project-upload"><h2>Upload project media</h2><p>Upload here without losing your unsaved project edits. Approved images and videos become available in the gallery above; add them to the gallery and save the project draft.</p>
<form method="post" action="{{ route('admin.media.store') }}" enctype="multipart/form-data" data-project-upload>@csrf
<input type="hidden" name="project_entry_id" value="{{ $entry->id }}"><input type="hidden" name="category" value="Projects"><input type="hidden" name="sort_order" value="0">
<label for="upload-file">File (JPEG, PNG, WebP, PDF or MP4; up to 20 MB)</label><input type="file" id="upload-file" name="file" accept=".jpg,.jpeg,.png,.webp,.pdf,.mp4" required>
<label for="upload-title">Media title</label><input id="upload-title" name="title" maxlength="180" required>
<label for="upload-alt">Image description for accessibility</label><input id="upload-alt" name="alt" maxlength="255">
<label for="upload-caption">Caption</label><input id="upload-caption" name="caption" maxlength="2000">
<label for="upload-source">Photographer / approval source</label><input id="upload-source" name="source" maxlength="255">
<input type="hidden" name="document_category" value="Project document">
@can('media.publish')<label for="upload-status">Publication</label><select id="upload-status" name="publication_status"><option value="draft">Private draft — review in Media library</option><option value="published">Approved for public use</option></select><label for="upload-access">Visitor access</label><select id="upload-access" name="is_public"><option value="0">Private</option><option value="1">Public when published</option></select>@else<input type="hidden" name="publication_status" value="draft"><input type="hidden" name="is_public" value="0">@endcan
@foreach(\App\Models\SiteSetting::current()['watermark'] as $key=>$value)<input type="hidden" name="watermark[{{ $key }}]" value="{{ is_bool($value) ? (int)$value : $value }}">@endforeach
<p class="muted">Uses the website watermark settings and keeps the original file unchanged.</p><button>Upload media</button><p data-upload-status role="status" aria-live="polite"></p>
</form></section>
@endcan
@endcan
<section id="project-publication"><h2>Review & publication</h2><p>{{ str($entry->status)->headline() }} · Version {{ $revision->version }}</p><a href="{{ route('admin.projects.preview',$entry) }}" target="_blank" rel="noopener">Preview saved draft ↗</a>
<form method="post" action="{{ route('admin.projects.transition',$entry) }}">@csrf<input type="hidden" name="version" value="{{ $revision->version }}"><label for="note">Review note</label><textarea id="note" name="note" rows="2"></textarea>
@if(in_array($entry->status,['draft','unpublished']))<button name="action" value="review">Submit for review</button>@endif
@can('publish',$entry)
@if($entry->status==='review')<button name="action" value="approve">Approve project</button>@endif
@if($entry->status==='approved')<button name="action" value="publish">Publish project</button><label for="schedule">Schedule ({{ config('app.timezone') }})</label><input type="datetime-local" name="scheduled_at" id="schedule"><button name="action" value="schedule">Schedule publication</button>@endif
@if(in_array($entry->status,['review','approved','scheduled']))<button name="action" value="return" class="quiet">Return to draft</button>@endif
@if($entry->published_revision_id)<button name="action" value="unpublish" class="quiet">Unpublish project</button>@endif
@if($entry->status!=='archived')<button name="action" value="archive" class="quiet">Archive project</button>@else<button name="action" value="restore">Restore as draft</button>@endif
@endcan
</form><details><summary>Revision history</summary>@foreach($entry->revisions()->latest('version')->get() as $item)<p>Version {{ $item->version }} · {{ $item->created_at }} @if($entry->published_revision_id===$item->id) · Published @endif</p>@endforeach</details></section>
@can('publish',$entry)<section><h2>Assigned project editors</h2><p>Assignments grant access only to users whose role includes assigned-project permissions.</p><form method="post" action="{{ route('admin.projects.assign',$entry) }}">@csrf<label for="assignees">Team members</label><select id="assignees" name="assignees[]" multiple size="5">@foreach($users as $user)<option value="{{ $user->id }}" @selected($entry->assignees->contains($user))>{{ $user->name }}</option>@endforeach</select><button>Save assignments</button></form></section>@endcan
@endif
<script src="{{ asset('assets/project-editor.js') }}?v={{ filemtime(public_path('assets/project-editor.js')) }}" defer></script>
@endsection
