@extends('layouts.admin')
@section('title', 'Location editor')
@section('content')
<p class="eyebrow">LOCATIONS & EXPANSION</p><h1>{{ $entry->exists ? $entry->title : 'Add a location' }}</h1><p><a href="{{ route('admin.locations.index') }}">← All locations</a></p>
<form method="post" action="{{ $entry->exists ? route('admin.locations.update',$entry) : route('admin.locations.store') }}">@csrf @if($entry->exists) @method('PUT') @endif<input type="hidden" name="version" value="{{ $revision?->version??0 }}">
<section><h2>Location details</h2><div class="form-grid">
<div><label for="title">Location name</label><input id="title" name="title" value="{{ old('title',$payload['title']??'') }}" required ></div><div><label for="slug">URL slug</label><input id="slug" name="slug" value="{{ old('slug',$payload['slug']??'') }}" required @readonly($entry->exists)></div><div><label for="level">Hierarchy level</label><select id="level" name="level">@foreach(\App\Services\LocationContent::LEVELS as $level)<option value="{{ $level }}" @selected(old('level',$payload['level']??'country')===$level) @disabled($entry->exists && ($payload['level']??'')!==$level)>{{ str($level)->headline() }}</option>@endforeach</select></div>
<div><label for="presence">Presence</label><select id="presence" name="presence"><option value="future" @selected(old('presence',$payload['presence']??'future')==='future')>Future / planned — not public</option><option value="current" @selected(old('presence',$payload['presence']??'future')==='current')>Current verified operations</option></select></div>
<div><label for="parent_id">Parent location</label><select id="parent_id" name="parent_id"><option value="">None (country only)</option>@foreach($parents as $parent)<option value="{{ $parent['id'] }}" @selected(old('parent_id',$payload['parent_id']??null)==$parent['id'])>{{ str($parent['level'])->headline() }} · {{ $parent['title'] }}</option>@endforeach</select></div></div></section>
<section><h2>Useful local content</h2><label for="summary">Introduction</label><textarea id="summary" name="summary" rows="4">{{ old('summary',$payload['summary']??'') }}</textarea><label for="body">Local experience and evidence</label><textarea id="body" name="body" rows="4">{{ old('body',$payload['body']??'') }}</textarea><label for="industries">Industries served</label><textarea id="industries" name="industries" rows="4">{{ old('industries',$payload['industries']??'') }}</textarea><label for="areas_served">Areas served</label><textarea id="areas_served" name="areas_served" rows="4">{{ old('areas_served',$payload['areas_served']??'') }}</textarea><label for="seo_description">SEO description</label><textarea id="seo_description" name="seo_description" rows="4">{{ old('seo_description',$payload['seo_description']??'') }}</textarea><label for="source_note">Internal evidence / approval reference</label><textarea id="source_note" name="source_note" rows="4">{{ old('source_note',$payload['source_note']??'') }}</textarea><label for="seo_title">SEO title</label><input id="seo_title" name="seo_title" value="{{ old('seo_title',$payload['seo_title']??'') }}"><input type="hidden" name="_submitted" value="1"></section><section><h2>Map coordinates</h2><p>Optional verified coordinates. Leave both blank when unknown.</p><div class="form-grid"><div><label for="latitude">Latitude</label><input id="latitude" type="number" step="any" min="-90" max="90" name="latitude" value="{{ old('latitude',$payload['latitude']??'') }}"></div><div><label for="longitude">Longitude</label><input id="longitude" type="number" step="any" min="-180" max="180" name="longitude" value="{{ old('longitude',$payload['longitude']??'') }}"></div></div><input type="hidden" name="verified" value="0"><label><input type="checkbox" name="verified" value="1" @checked(old('verified',$payload['verified']??false))> This location information is verified and approved.</label><button>{{ \App\Services\ContentPublisher::immediate() ? 'Save location' : 'Save location draft' }}</button></section></form>
@if($entry->exists) @include('admin.content.workflow') @endif
@endsection
