@extends('layouts.public')
@section('content')
<section class="corporate-hero"><div class="corporate-container"><p class="eyebrow">PROJECTS</p><h1>Our work defines us.</h1><p class="lead">Explore our project portfolio and construction progress.</p></div></section>
<div class="corporate-container corporate-detail">
<form class="project-filters" method="get"><div><label for="status">Status</label><select id="status" name="status"><option value="">All statuses</option>@foreach(\App\Services\ProjectContent::STATUSES as $option)<option @selected(($filters['status']??'')===$option)>{{ $option }}</option>@endforeach</select></div><div><label for="sector">Sector</label><select id="sector" name="sector"><option value="">All sectors</option>@foreach(\App\Services\ProjectContent::SECTORS as $option)<option @selected(($filters['sector']??'')===$option)>{{ $option }}</option>@endforeach</select></div><div><label for="city">Location</label><select id="city" name="city"><option value="">All locations</option>@foreach($cities as $city)<option @selected(($filters['city']??'')===$city)>{{ $city }}</option>@endforeach</select></div><button class="button ink">Filter projects</button><a href="{{ route('projects.index') }}">Reset</a></form>
<div class="project-cards">@forelse($items as $item)<article>@include('partials.card-image', ['card' => $item])
<p class="eyebrow">{{ $item['sector'] }} · {{ $item['status'] }}</p><h2><a href="{{ $item['url'] }}">{{ $item['title'] }}</a></h2><p>{{ $item['city'] }}</p><p>{{ $item['stage'] }} — {{ $item['progress'] }}% complete</p><progress value="{{ $item['progress'] }}" max="100">{{ $item['progress'] }}%</progress><a class="text-link dark-link" href="{{ $item['url'] }}">Explore project ↗</a></article>@empty<article><h2>{{ request()->filled('status') || request()->filled('sector') || request()->filled('city') ? 'No matching projects.' : 'Project updates will appear here.' }}</h2><p>{{ request()->filled('status') || request()->filled('sector') || request()->filled('city') ? 'Try another filter to explore the portfolio.' : 'Approved project information and site updates will be added as they become available.' }}</p></article>@endforelse</div>
</div>
@endsection
