@extends('layouts.public')
@section('content')
<article><section class="corporate-hero"><div class="corporate-container"><nav class="corporate-breadcrumb" aria-label="Breadcrumb"><a href="{{ route('home') }}">Home</a><span>/</span><a href="{{ route('projects.index') }}">Projects</a></nav><p class="eyebrow">{{ $payload['project_type'] }} · {{ $payload['status'] }}</p><h1>{{ $payload['title'] }}</h1><p class="lead">{{ ($payload['location']??'') ?: $payload['city'] }}</p><p>{{ $payload['stage'] }} — {{ $payload['progress'] }}% complete</p><progress value="{{ $payload['progress'] }}" max="100">{{ $payload['progress'] }}%</progress><p>Last updated: {{ $payload['progress_date'] }}</p></div></section>
<div class="corporate-container corporate-detail">
@if($cover=$media->get($payload['cover_media_id']??null))<figure class="corporate-cover"><img src="{{ route('media.show',$cover) }}" alt="{{ $cover->alt }}" width="1200" height="800" fetchpriority="high"></figure>@endif
<div class="cms-prose">{{ $payload['description']??'' }}</div><dl class="corporate-facts">
@foreach(['sector'=>'Sector','city'=>'City','state'=>'State','country'=>'Country','project_area'=>'Project area','built_up_area'=>'Built-up area','start_date'=>'Start date','expected_completion'=>'Expected completion','actual_completion'=>'Completion date'] as $key=>$label)
@if($payload[$key]??null)<div><dt>{{ $label }}</dt><dd>{{ $payload[$key] }}</dd></div>@endif
@endforeach
@if(($payload['client_approved']??false) && ($payload['client']??null))<div><dt>Client / partner</dt><dd>{{ $payload['client'] }}</dd></div>@endif
@if(($payload['value_approved']??false) && ($payload['project_value']??null))<div><dt>Project value</dt><dd>{{ $payload['project_value'] }}</dd></div>@endif
</dl>
@foreach(['scope'=>'Our scope','engineering'=>'Engineering','construction'=>'Construction','management'=>'Project management','technical_highlights'=>'Technical highlights','quality_safety'=>'Quality & safety','outcome'=>'Project outcome'] as $key=>$label)
@if($payload[$key]??null)<section class="corporate-group"><h2>{{ $label }}</h2><div class="cms-prose">{{ $payload[$key] }}</div></section>@endif
@endforeach
@if($equipment->isNotEmpty())<section class="corporate-group"><h2>Equipment used</h2>@foreach($equipment as $item)<p><a href="{{ route('corporate.equipment',$item['slug']) }}">{{ $item['title'] }} ↗</a></p>@endforeach</section>@endif
@if($payload['timeline']??[])<section class="corporate-group"><h2>Construction progress</h2><div class="stage-control" hidden><label for="stage-range">Explore construction stages</label><input id="stage-range" type="range" min="0" max="{{ count($payload['timeline'])-1 }}" value="0"><output for="stage-range" aria-live="polite"></output><button type="button" class="button ink" data-all-stages>Show all stages</button></div><ol class="project-timeline">@foreach($payload['timeline'] as $stage)<li><h3>{{ $stage['name'] }}</h3><p>{{ $stage['progress'] }}% complete @if($stage['date']??null) · {{ $stage['date'] }} @endif</p><progress value="{{ $stage['progress'] }}" max="100">{{ $stage['progress'] }}%</progress><p>{{ $stage['description']??'' }}</p>@if($stage['milestone']??null)<p><strong>Milestone:</strong> {{ $stage['milestone'] }}</p>@endif @if($image=$media->get($stage['media_id']??null))<img src="{{ route('media.show',$image) }}" alt="{{ $image->alt }}" loading="lazy" width="600" height="400">@endif</li>@endforeach</ol></section>@endif
@if(($before=$media->get($payload['before_media_id']??null)) && ($after=$media->get($payload['after_media_id']??null)))<section class="corporate-group"><h2>Progress comparison</h2><div class="corporate-gallery"><figure><img src="{{ route('media.show',$before) }}" alt="{{ $before->alt }}" loading="lazy" width="800" height="600"><figcaption>Before</figcaption></figure><figure><img src="{{ route('media.show',$after) }}" alt="{{ $after->alt }}" loading="lazy" width="800" height="600"><figcaption>After</figcaption></figure></div></section>@endif
@if(collect($payload['gallery']??[])->contains(fn($row)=>($row['visible']??false) && $media->has($row['media_id'])))<section class="corporate-group"><h2>From the site</h2><div class="gallery-control" hidden><label for="gallery-category">Gallery category</label><select id="gallery-category"><option value="">All media</option>@foreach(collect($payload['gallery'])->where('visible',true)->pluck('category')->unique() as $category)<option>{{ $category }}</option>@endforeach</select></div><div class="corporate-gallery project-gallery">@foreach($payload['gallery'] as $row)
@if(($row['visible']??false) && ($asset=$media->get($row['media_id'])))<figure data-category="{{ $row['category'] }}">
@if($asset->mime==='video/mp4')<video controls playsinline preload="none" aria-label="{{ ($row['caption']??'') ?: $asset->title }}"><source src="{{ route('media.show',$asset) }}" type="video/mp4"></video>@else<a href="{{ route('media.show',$asset) }}"><img src="{{ route('media.show',$asset) }}" alt="{{ ($row['alt']??'') ?: $asset->alt }}" loading="lazy" width="800" height="600"></a>@endif
<figcaption><strong>{{ $row['category'] }}</strong> {{ $row['caption']??'' }} @if($row['date']??null) · {{ $row['date'] }} @endif @if($row['stage']??null) · {{ $row['stage'] }} @endif @if($row['location']??null) · {{ $row['location'] }} @endif</figcaption>@if($row['description']??null)<p>{{ $row['description'] }}</p>@endif</figure>@endif
@endforeach</div></section>@endif
@if($payload['document_ids']??[])<section class="corporate-group"><h2>Project documents</h2>@foreach($payload['document_ids'] as $id) @if($document=$media->get($id))<p><a href="{{ route('media.show',$document) }}">{{ $document->title }} (PDF) ↓</a></p>@endif @endforeach</section>@endif
@if($payload['faqs']??[])<section class="corporate-group"><h2>Project questions</h2>@foreach($payload['faqs'] as $faq)<details><summary>{{ $faq['question'] }}</summary><p class="cms-prose">{{ $faq['answer'] }}</p></details>@endforeach</section>@endif
@if($related->isNotEmpty())<section class="corporate-group"><h2>Related projects</h2>@foreach($related as $item)<p><a href="{{ $item['url'] }}">{{ $item['title'] }} ↗</a></p>@endforeach</section>@endif
<aside class="corporate-callout"><h2>Discuss a similar project.</h2><a class="button ink" href="{{ route('home') }}#contact">Start a conversation ↗</a></aside>
</div></article>
<script src="{{ asset('assets/project-viewer.js') }}" defer></script>
@endsection
