@extends('layouts.admin')
@section('title','Media editor')
@section('content')<h1>{{ $media->exists ? 'Edit media.' : 'Upload media.' }}</h1>
@if($media->exists)<p><a href="{{ route('admin.media.original',$media) }}">Download untouched original</a></p>@if(str_starts_with($media->mime,'image/'))<img class="media-preview" src="{{ route('media.show',$media) }}" alt="{{ $media->alt }}">@endif @endif
<form method="post" enctype="multipart/form-data" action="{{ $media->exists ? route('admin.media.update',$media) : route('admin.media.store') }}">@csrf @if($media->exists) @method('PUT') @else<label for="file">File (JPEG, PNG, WebP, PDF or MP4; up to 20 MB)</label><input type="file" id="file" name="file" accept=".jpg,.jpeg,.png,.webp,.pdf,.mp4" required><p>Images: up to 24 megapixels. Web images are resized to a maximum of 1,920 pixels.</p>@endif
@foreach(['title'=>'Title','alt'=>'Image description for accessibility','caption'=>'Caption','description'=>'Description','project'=>'Project','location'=>'Location','source'=>'Photographer / source'] as $key=>$label)<label for="{{ $key }}">{{ $label }}</label><input name="{{ $key }}" id="{{ $key }}" value="{{ old($key,$media->$key) }}" @required($key==='title')>@endforeach
<label for="category">Category</label><select id="category" name="category">@foreach(['Projects','Machinery','Team','Careers','Company','Videos','Documents','Social'] as $category)<option @selected(old('category',$media->category)===$category)>{{ $category }}</option>@endforeach</select>
<label for="taken_at">Image date</label><input type="date" id="taken_at" name="taken_at" value="{{ old('taken_at',$media->taken_at?->format('Y-m-d')) }}">
<label for="document_category">Document category (PDFs)</label><select id="document_category" name="document_category"><option value="">Not a document</option>@foreach(['Company profile','Brochure','Certification','Award','Project document','Policy','Career','Other'] as $category)<option @selected(old('document_category',$media->document_category)===$category)>{{ $category }}</option>@endforeach</select>
@if(\App\Services\ContentPublisher::immediate())<input type="hidden" name="publication_status" value="published">@else<label for="publication_status">Publication status</label><select id="publication_status" name="publication_status">@foreach(['draft','published'] as $state)<option value="{{ $state }}" @selected(old('publication_status',$media->publication_status)===$state)>{{ str($state)->headline() }}</option>@endforeach</select>@endif
<label for="is_public">Visitor access</label><select id="is_public" name="is_public"><option value="0" @selected(!old('is_public',$media->is_public))>Private</option><option value="1" @selected(old('is_public',$media->is_public))>Public</option></select><p>Only publish files approved for visitors. Private files cannot be used in the public homepage.</p>
<label for="sort_order">Display order</label><input type="number" name="sort_order" id="sort_order" min="0" max="1000" value="{{ old('sort_order',$media->sort_order) }}">
<fieldset><legend>Brand watermark (images only)</legend><p>{{ config('app.name') }}</p><label for="watermark-enabled">Watermark</label><select id="watermark-enabled" name="watermark[enabled]"><option value="0" @selected(!old('watermark.enabled',$media->watermark['enabled']))>Off</option><option value="1" @selected(old('watermark.enabled',$media->watermark['enabled']))>On</option></select>
<label for="position">Position</label><select id="position" name="watermark[position]">@foreach(['bottom-left','bottom-right','top-left','top-right','center'] as $position)<option value="{{ $position }}" @selected(old('watermark.position',$media->watermark['position'])===$position)>{{ str($position)->headline() }}</option>@endforeach</select>
@foreach(['opacity'=>['Opacity (%)',10,100],'size'=>['Size (1–5)',1,5],'padding'=>['Padding (pixels)',0,100]] as $key=>$options)<label for="watermark-{{ $key }}">{{ $options[0] }}</label><input type="number" name="watermark[{{ $key }}]" id="watermark-{{ $key }}" min="{{ $options[1] }}" max="{{ $options[2] }}" value="{{ old('watermark.'.$key,$media->watermark[$key]) }}">@endforeach</fieldset><button>Save media</button></form>@if($media->exists)<form method="post" action="{{ route('admin.media.archive',$media) }}">@csrf<input type="hidden" name="action" value="{{ $media->archived_at?'restore':'archive' }}"><button class="quiet">{{ $media->archived_at?'Restore as draft':'Archive and remove from website' }}</button></form>@endif
@endsection
