@extends('layouts.admin')
@section('title','Candidate application')
@section('content')
<p class="eyebrow">PRIVATE APPLICATION</p><h1>{{ $candidate->name }}</h1><p>{{ $candidate->job_title }} · {{ $candidate->status }}</p><a href="{{ route('admin.candidates.index') }}">← Candidate pipeline</a>
<section><h2>Application details</h2><p>{{ $candidate->email }} · {{ $candidate->phone }}</p><dl class="profile-details">@foreach($candidate->profile as $key=>$value) @if($value)<dt>{{ str($key)->headline() }}</dt><dd>{{ $value }}</dd>@endif @endforeach</dl><p>Recruitment consent received {{ $candidate->consented_at->format('d M Y H:i') }}.</p><a class="button" href="{{ route('admin.candidates.resume',$candidate) }}">Download résumé (PDF)</a></section>
@if($candidate->accessibleBy(auth()->user(),'edit'))<section><h2>Recruitment review</h2><form method="post" action="{{ route('admin.candidates.update',$candidate) }}">@csrf @method('PUT')<input type="hidden" name="version" value="{{ $candidate->version }}"><label for="status">Pipeline stage</label><select id="status" name="status">@foreach(\App\Models\Candidate::STATUSES as $status)<option @selected(old('status',$candidate->status)===$status)>{{ $status }}</option>@endforeach</select>
@can('candidates.edit')<label for="assigned_to">Assigned recruiter</label><select id="assigned_to" name="assigned_to"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('assigned_to',$candidate->assigned_to)==$user->id)>{{ $user->name }}</option>@endforeach</select>@endcan
<label for="interview_at">Interview date and time ({{ config('app.timezone') }})</label><input type="datetime-local" id="interview_at" name="interview_at" value="{{ old('interview_at',$candidate->interview_at?->format('Y-m-d\TH:i')) }}"><label for="interview_notes">Interview notes</label><textarea id="interview_notes" name="interview_notes" rows="5">{{ old('interview_notes',$candidate->interview_notes) }}</textarea><label for="internal_notes">Internal notes</label><textarea id="internal_notes" name="internal_notes" rows="5">{{ old('internal_notes',$candidate->internal_notes) }}</textarea><button>Save candidate review</button></form></section>@endif
@endsection
