@extends('layouts.admin')
@section('title','Campaign editor')
@section('content')
<p class="eyebrow">CAMPAIGN LANDING PAGE</p><h1>{{ $entry->exists ? $entry->title : 'Create a campaign' }}</h1><p><a href="{{ route('admin.campaigns.index') }}">← Campaigns</a></p><form method="post" action="{{ $entry->exists ? route('admin.campaigns.update',$entry) : route('admin.campaigns.store') }}">@csrf @if($entry->exists) @method('PUT') @endif<input type="hidden" name="version" value="{{ $revision?->version??0 }}"><section><h2>Message & destination</h2><div class="form-grid">@foreach(['title'=>'Campaign name','slug'=>'URL slug','headline'=>'Headline','subheadline'=>'Subheadline','cta_label'=>'Enquiry button label','seo_title'=>'SEO title','seo_description'=>'Meta description'] as $key=>$label)<div><label for="{{ $key }}">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" value="{{ old($key,$payload[$key]??'') }}" @readonly($key==='slug' && $entry->exists)></div>@endforeach</div><label for="body">Page content</label><textarea name="body" id="body" rows="8">{{ old('body',$payload['body']??'') }}</textarea><label for="form_type">Enquiry form</label><select name="form_type" id="form_type">@foreach(\App\Services\EnquiryForms::enabled() as $type=>$form)<option value="{{ $type }}" @selected(old('form_type',$payload['form_type']??'')===$type)>{{ $type }}</option>@endforeach</select><label for="cover_media_id">Hero image or video</label><select name="cover_media_id" id="cover_media_id"><option value="">None</option>@foreach($mediaItems as $item)<option value="{{ $item->id }}" @selected(old('cover_media_id',$payload['cover_media_id']??null)==$item->id)>{{ $item->title }}</option>@endforeach</select></section>
<section><h2>Approved content & proof</h2><div class="form-grid">@foreach($options->groupBy('type') as $type=>$records)<fieldset><legend>{{ \App\Services\KnowledgeContent::TYPES[$type]??str($type)->plural()->headline() }}</legend>@foreach($records as $item)<label><input type="checkbox" name="related_ids[]" value="{{ $item['id'] }}" @checked(in_array($item['id'],old('related_ids',$payload['related_ids']??[])))> {{ $item['title'] }}</label>@endforeach</fieldset>@endforeach<fieldset><legend>Statistics</legend>@foreach($statistics as $item)<label><input type="checkbox" name="statistic_ids[]" value="{{ $item['id'] }}" @checked(in_array($item['id'],old('statistic_ids',$payload['statistic_ids']??[])))> {{ $item['title'] }}</label>@endforeach</fieldset></div><label for="source_note">Internal approval reference</label><textarea id="source_note" name="source_note" rows="3">{{ old('source_note',$payload['source_note']??'') }}</textarea><input type="hidden" name="verified" value="0"><label><input type="checkbox" name="verified" value="1" @checked(old('verified',$payload['verified']??false))> Campaign claims and content have been verified.</label><button>Save draft</button></section></form>
@if($entry->exists)<section><h2>Review & publication</h2><p>{{ str($entry->status)->headline() }} · Version {{ $revision->version }}</p><a href="{{ route('admin.campaigns.preview',$entry) }}">Preview saved draft ↗</a><form method="post" action="{{ route('admin.campaigns.transition',$entry) }}">@csrf<input type="hidden" name="version" value="{{ $revision->version }}"><label for="note">Review note</label><input id="note" name="note" maxlength="1000">@if(in_array($entry->status,['draft','unpublished']))<button name="action" value="review">Submit for review</button>@endif
@can('pages.approve')@if($entry->status==='review')<button name="action" value="approve">Approve</button>@endif @if(in_array($entry->status,['review','approved','scheduled']))<button name="action" value="return">Return to draft</button>@endif @endcan
@can('pages.publish')@if($entry->status==='approved')<button name="action" value="publish">Publish</button><label for="scheduled_at">Scheduled publication (UTC)</label><input type="datetime-local" name="scheduled_at" id="scheduled_at"><button name="action" value="schedule">Schedule</button>@endif @endcan
@can('pages.unpublish')@if($entry->published_revision_id)<button name="action" value="unpublish">Unpublish</button>@endif @endcan
@can('pages.archive')@if($entry->status!=='archived')<button name="action" value="archive">Archive</button>@endif @endcan
@if($entry->status==='archived')<button name="action" value="restore">Restore as draft</button>@endif</form></section>@endif
@endsection
