@extends('layouts.admin')
@section('title','Lead details')
@section('content')
<p class="eyebrow">{{ $enquiry->type }} · LEAD #{{ $enquiry->id }}</p><h1>{{ $enquiry->name }}</h1><a href="{{ route('admin.enquiries') }}">← All enquiries</a>
<section><h2>Requirement</h2><p>{{ $enquiry->email }} · {{ $enquiry->phone }} · {{ $enquiry->location }}</p><p class="cms-prose">{{ $enquiry->message }}</p>@foreach($enquiry->details??[] as $key=>$value)@if($value)<p><strong>{{ \App\Services\EnquiryForms::FIELDS[$key]??str($key)->headline() }}:</strong> {{ $value }}</p>@endif @endforeach<p>Received {{ $enquiry->created_at }} UTC · Consent recorded {{ $enquiry->consented_at }} UTC</p></section>
<section><h2>Source & context</h2><p>Campaign and CTA values are supplied by the visitor’s link; they are attribution hints.</p>@forelse($enquiry->attribution??[] as $key=>$value)@if($value)<p><strong>{{ str($key)->headline() }}:</strong> {{ $value }}</p>@endif @empty<p>No attribution was captured for this earlier enquiry.</p>@endforelse</section>
@if($enquiry->accessibleBy(auth()->user(),'edit'))<section><h2>Manage lead</h2><form method="post" action="{{ route('admin.enquiries.update',$enquiry) }}">@csrf @method('PUT')<input type="hidden" name="version" value="{{ $enquiry->version }}"><div class="form-grid"><div><label for="status">Pipeline status</label><select id="status" name="status">@foreach(\App\Models\Enquiry::STATUSES as $status)<option value="{{ $status }}" @selected(old('status',$enquiry->status)===$status)>{{ str($status)->headline() }}</option>@endforeach</select></div><div><label for="qualification">Qualification</label><select id="qualification" name="qualification">@foreach(['pending','qualified','unqualified'] as $value)<option value="{{ $value }}" @selected(old('qualification',$enquiry->qualification)===$value)>{{ ucfirst($value) }}</option>@endforeach</select></div><div><label for="follow_up_at">Next follow-up (UTC)</label><input type="datetime-local" id="follow_up_at" name="follow_up_at" value="{{ old('follow_up_at',$enquiry->follow_up_at?->format('Y-m-d\TH:i')) }}"></div>@can('leads.assign')<div><label for="assigned_to">Assigned team member</label><select id="assigned_to" name="assigned_to"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('assigned_to',$enquiry->assigned_to)==$user->id)>{{ $user->name }}</option>@endforeach</select></div>@endcan</div><label for="note">Add a private note</label><textarea id="note" name="note" rows="4" maxlength="10000">{{ old('note') }}</textarea><button>Save lead update</button></form></section>@endif
<section><h2>Activity & notes</h2>@forelse($enquiry->notes->sortByDesc('id') as $note)<article><p><strong>{{ $note->author?->name??'Former team member' }}</strong> · {{ $note->created_at }} UTC</p>@if($note->body)<p class="cms-prose">{{ $note->body }}</p>@endif @foreach($note->changes??[] as $key=>$change)<p>{{ str($key)->headline() }}: {{ $change['before']??'—' }} → {{ $change['after']??'—' }}</p>@endforeach</article>@empty<p>No updates yet.</p>@endforelse</section>
@endsection
