@extends('layouts.admin')
@section('title','Users')
@section('content')<p class="eyebrow">ACCESS MANAGEMENT</p><h1>People & access.</h1><p>Assign the least access each person needs. Changes take effect on their next request.</p>
<div class="cards">@foreach($users as $user)<section><h2>{{ $user->name }}</h2><p>{{ $user->email }}</p>@if($user->hasRole('super-admin'))
<span class="tag">Primary Super Admin · Active</span><p class="muted">Full access. This primary account is protected from role and status changes.</p>
@if($user->is(auth()->user()))<a href="{{ route('admin.account') }}">Personal settings →</a>@endif
@else
<form method="post" action="{{ route('admin.users.update',$user) }}">@csrf @method('PATCH')<label for="role-{{ $user->id }}">Role</label><select id="role-{{ $user->id }}" name="role_id">@foreach($roles as $role)<option value="{{ $role->id }}" @selected($user->roles->contains($role))>{{ $role->label }}</option>@endforeach</select><label for="active-{{ $user->id }}">Account status</label><select id="active-{{ $user->id }}" name="is_active"><option value="1" @selected($user->is_active)>Active</option><option value="0" @selected(!$user->is_active)>Inactive</option></select><button>Save access</button></form>
@endif
</section>@endforeach</div>{{ $users->links('pagination') }}
<section><h2>Add a user</h2><form method="post" action="{{ route('admin.users.store') }}" class="form-grid">@csrf<div><label for="name">Full name</label><input id="name" name="name" value="{{ old('name') }}" required maxlength="150"></div><div><label for="email">Email address</label><input id="email" type="email" name="email" value="{{ old('email') }}" required></div><div><label for="new-password">Password (8+ characters, letters and numbers)</label><input id="new-password" type="password" name="password" autocomplete="new-password" required minlength="8"></div><div><label for="password-confirmation">Confirm password</label><input id="password-confirmation" type="password" name="password_confirmation" autocomplete="new-password" required></div><div><label for="role">Role</label><select id="role" name="role_id" required><option value="">Choose a role</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected(old('role_id')==$role->id)>{{ $role->label }}</option>@endforeach</select></div><div><button>Create user</button></div></form></section>@endsection
