@extends('layouts.admin')
@section('title','Editorial content')
@section('content')
<p class="eyebrow">BLOG / KNOWLEDGE / FAQS</p><h1>{{ $entry->exists ? $entry->title : 'Create editorial content' }}</h1><p><a href="{{ route('admin.knowledge.index') }}">← Editorial library</a></p>
<form method="post" action="{{ $entry->exists ? route('admin.knowledge.update',$entry) : route('admin.knowledge.store') }}">@csrf @if($entry->exists) @method('PUT') @endif<input type="hidden" name="version" value="{{ $revision?->version??0 }}">
<section><h2>Content & topic</h2><div class="form-grid"><div><label for="type">Content type</label><select id="type" name="type">@foreach(\App\Services\KnowledgeContent::TYPES as $key=>$label)<option value="{{ $key }}" @selected(old('type',$entry->type)===$key) @disabled($entry->exists && $entry->type!==$key)>{{ $label }}</option>@endforeach</select></div>
@foreach(['title'=>'Title / question','slug'=>'URL slug','category'=>'Category','topic'=>'Topic cluster'] as $key=>$label)<div><label for="{{ $key }}">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" value="{{ old($key,$payload[$key]??'') }}" @readonly($key==='slug' && $entry->exists)></div>@endforeach</div>
<label for="short_answer">Short direct answer / summary</label><textarea id="short_answer" name="short_answer" rows="3">{{ old('short_answer',$payload['short_answer']??'') }}</textarea><label for="body">Detailed answer / article</label><textarea id="body" name="body" rows="12">{{ old('body',$payload['body']??'') }}</textarea><label for="explanation">Supporting explanation</label><textarea id="explanation" name="explanation" rows="5">{{ old('explanation',$payload['explanation']??'') }}</textarea></section>
<section><h2>Related content</h2><p>Choose published records to connect this content to services, projects, locations, pages and other answers. Links also appear on the related pages.</p><div class="form-grid">@foreach($options->groupBy('type') as $type=>$records)<fieldset><legend>{{ \App\Services\KnowledgeContent::TYPES[$type]??str($type)->plural()->headline() }}</legend>@foreach($records as $item)<label><input type="checkbox" name="related_ids[]" value="{{ $item['id'] }}" @checked(in_array($item['id'],old('related_ids',$payload['related_ids']??[])))> {{ $item['title'] }}</label>@endforeach</fieldset>@endforeach</div></section>
<section><h2>Review & attribution</h2><div class="form-grid">@foreach(['author'=>'Public author name','reviewer'=>'Public reviewer name','seo_title'=>'SEO title','seo_description'=>'Meta description'] as $key=>$label)<div><label for="{{ $key }}">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" value="{{ old($key,$payload[$key]??'') }}"></div>@endforeach</div><label for="source_note">Internal evidence / approval reference</label><textarea id="source_note" name="source_note" rows="3">{{ old('source_note',$payload['source_note']??'') }}</textarea>
@foreach(['verified'=>'Facts and attribution have been verified','featured'=>'Feature this content','schema_enabled'=>'Allow eligible structured data'] as $key=>$label)<input type="hidden" name="{{ $key }}" value="0"><label><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$payload[$key]??false))> {{ $label }}</label>@endforeach<label for="order">Sort order</label><input type="number" id="order" name="order" min="0" max="9999" value="{{ old('order',$payload['order']??0) }}"><button>Save draft</button></section></form>
@if($entry->exists)<section><h2>Publication</h2><p>{{ str($entry->status)->headline() }} · Version {{ $revision->version }}</p><a href="{{ route('admin.knowledge.preview',$entry) }}">Preview saved draft ↗</a><form method="post" action="{{ route('admin.content.transition',$entry) }}">@csrf<input type="hidden" name="version" value="{{ $revision->version }}"><label for="note">Review note</label><input id="note" name="note" maxlength="1000">
@if(in_array($entry->status,['draft','unpublished']))<button name="action" value="review">Submit for review</button>@endif
@can('pages.approve')@if($entry->status==='review')<button name="action" value="approve">Approve</button>@endif @if(in_array($entry->status,['review','approved','scheduled']))<button name="action" value="return">Return to draft</button>@endif @endcan
@can('pages.publish')@if($entry->status==='approved')<button name="action" value="publish">Publish</button><label for="scheduled_at">Or schedule publication</label><input type="datetime-local" name="scheduled_at" id="scheduled_at"><button name="action" value="schedule">Schedule</button>@endif @endcan
@can('pages.unpublish')@if($entry->published_revision_id)<button name="action" value="unpublish">Unpublish</button>@endif @endcan
@can('pages.archive')@if($entry->status!=='archived')<button name="action" value="archive">Archive</button>@endif @endcan
@if($entry->status==='archived')<button name="action" value="restore">Restore as draft</button>@endif
</form></section>@endif
@endsection
