@extends('layouts.admin')
@section('title','Content editor')
@section('content')<h1>{{ $entry->exists ? 'Edit content.' : 'Create content.' }}</h1>
<form method="post" action="{{ $entry->exists ? route('admin.content.update',$entry) : route('admin.content.store') }}">@csrf @if($entry->exists) @method('PUT') @endif
<input type="hidden" name="version" value="{{ $revision?->version ?? 0 }}">
<label for="type">Content type</label><select id="type" name="type" @if($entry->exists) disabled @endif>@foreach(['page'=>'Page','block'=>'Reusable text block','statistic'=>'Company statistic','menu'=>'Navigation link'] as $key=>$label)<option value="{{ $key }}" @selected(old('type',$entry->type)===$key)>{{ $label }}</option>@endforeach</select>@if($entry->exists)<input type="hidden" name="type" value="{{ $entry->type }}">@endif
<label for="slug">Unique name / page address</label><input id="slug" name="slug" value="{{ old('slug',$entry->slug) }}" pattern="[a-zA-Z0-9_-]+" required @readonly($entry->exists)><p>Use lowercase words separated by hyphens. Page addresses use /pages/your-name. The address is fixed after creation.</p>
@foreach(['title'=>'Title / navigation label','description'=>'Search description','value'=>'Statistic value (statistics only)','url'=>'Link address (navigation only, e.g. /#contact)'] as $key=>$label)<label for="{{ $key }}">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" value="{{ old($key,$payload[$key]??'') }}" @required($key==='title')>@endforeach
<label for="body">Page or reusable block text</label><textarea id="body" name="body" rows="12">{{ old('body',$payload['body']??'') }}</textarea><p>Plain text. Paragraphs are preserved; HTML is displayed as text.</p>
<label for="placement">Navigation placement</label><select id="placement" name="placement">@foreach(['both'=>'Header and footer','header'=>'Header only','footer'=>'Footer only'] as $key=>$label)<option value="{{ $key }}" @selected(old('placement',$payload['placement']??'both')===$key)>{{ $label }}</option>@endforeach</select>
<label for="order">Display order (lower numbers first)</label><input id="order" type="number" name="order" min="0" max="1000" value="{{ old('order',$payload['order']??0) }}">
<fieldset><legend>Reuse on this page</legend><p>Selected blocks and statistics use their latest published version wherever they appear.</p>@foreach(['block_ids'=>$blocks,'statistic_ids'=>$statistics] as $key=>$items) @foreach($items as $item)<label><input type="checkbox" name="{{ $key }}[]" value="{{ $item->id }}" @checked(in_array($item->id,old($key,$payload[$key]??[])))> {{ $item->title }} ({{ $item->type }})</label>@endforeach @endforeach</fieldset><button>Save draft</button></form>
@if($entry->exists) @include('admin.content.workflow') @endif @endsection
