@extends('layouts.admin')
@section('title','Content editor')
@section('content')<h1>{{ $entry->exists ? 'Edit content.' : 'Create content.' }}</h1>
<form method="post" action="{{ $entry->exists ? route('admin.content.update',$entry) : route('admin.content.store') }}">@csrf @if($entry->exists) @method('PUT') @endif
<input type="hidden" name="version" value="{{ $revision?->version ?? 0 }}">
<p>Content type: {{ $entry->type==='cta'?'Call to action':str($entry->type)->headline() }} · <a href="{{ route('admin.content.index') }}">Choose another type</a></p><input type="hidden" name="type" value="{{ $entry->type }}">
<label for="slug">Unique name / page address</label><input id="slug" name="slug" value="{{ old('slug',$entry->slug) }}" pattern="[a-zA-Z0-9_-]+" required @readonly($entry->exists)><p>Use lowercase words separated by hyphens. Page addresses use /pages/your-name. The address is fixed after creation.</p>
@php($editorFields=match($entry->type){'statistic'=>['title'=>'Statistic label','value'=>'Verified value'],'menu','cta'=>['title'=>'Link label','url'=>'Link address (e.g. /#contact)'],'block'=>['title'=>'Block title'],default=>['title'=>'Page title','description'=>'Search description']})
@foreach($editorFields as $key=>$label)<label for="{{ $key }}">{{ $label }}</label><input id="{{ $key }}" name="{{ $key }}" value="{{ old($key,$payload[$key]??'') }}" @required($key!=='description')>@endforeach
@if(in_array($entry->type,['page','block']))<label for="body">Text</label><textarea id="body" name="body" rows="12">{{ old('body',$payload['body']??'') }}</textarea><p>Plain text. Paragraphs are preserved; HTML is displayed as text.</p>@endif
@if($entry->type==='menu')<label for="placement">Navigation placement</label><select id="placement" name="placement">@foreach(['both'=>'Header and footer','header'=>'Header only','footer'=>'Footer only'] as $key=>$label)<option value="{{ $key }}" @selected(old('placement',$payload['placement']??'both')===$key)>{{ $label }}</option>@endforeach</select>@else<input type="hidden" name="placement" value="both">@endif
<label for="order">Display order (lower numbers first)</label><input id="order" type="number" name="order" min="0" max="1000" value="{{ old('order',$payload['order']??0) }}">
@if($entry->type==='page')<fieldset><legend>Reuse on this page</legend><p>Selected blocks and statistics use their latest published version wherever they appear.</p>@foreach(['block_ids'=>$blocks,'statistic_ids'=>$statistics,'cta_ids'=>$ctas] as $key=>$items) @foreach($items as $item)<label><input type="checkbox" name="{{ $key }}[]" value="{{ $item->id }}" @checked(in_array($item->id,old($key,$payload[$key]??[])))> {{ $item->title }} ({{ $item->type }})</label>@endforeach @endforeach
@foreach($documents as $document)<label><input type="checkbox" name="document_ids[]" value="{{ $document->id }}" @checked(in_array($document->id,old('document_ids',$payload['document_ids']??[])))> {{ $document->title }} (PDF download)</label>@endforeach</fieldset>@endif<button>{{ \App\Services\ContentPublisher::immediate() ? 'Save' : 'Save draft' }}</button></form>
@if($entry->exists) @include('admin.content.workflow') @endif @endsection
