<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>@yield('title', 'Administration') | {{ config('app.name') }}</title><link rel="stylesheet" href="{{ asset('assets/admin.css') }}"><script src="{{ asset('assets/password-toggle.js') }}" defer></script></head>
<body><a class="skip" href="#main">Skip to content</a><header><a class="brand" href="{{ route('home') }}">{{ config('app.name') }}</a><span class="badge">ADMINISTRATION</span></header>
@auth
@if(\App\Http\Middleware\RequireTwoFactor::enforced() && auth()->user()->hasRole('super-admin') && (!auth()->user()->two_factor_confirmed_at || session('admin.setup_recovery_pending')))
<nav aria-label="Account setup"><a href="{{ route('admin.security') }}">Complete account setup</a><span>CMS access opens after authenticator setup.</span><form method="post" action="{{ route('logout') }}">@csrf<button class="quiet">Sign out</button></form></nav>
@else
<nav aria-label="Administration"><a href="{{ route('admin.dashboard') }}">Overview</a>@can('users.manage')<a href="{{ route('admin.users.index') }}">Users</a>@endcan @can('roles.view')<a href="{{ route('admin.roles') }}">Roles & permissions</a>@endcan @can('audit.view')<a href="{{ route('admin.audit') }}">Audit log</a>@endcan
@can('pages.edit')<a href="{{ route('admin.homepage.edit') }}">Homepage</a><a href="{{ route('admin.content.index') }}">Pages & reusable content</a>@endcan
@can('pages.view')<a href="{{ route('admin.corporate.index') }}">Company & capabilities</a>@endcan
@can('media.manage')<a href="{{ route('admin.media.index') }}">Media library</a>@endcan
@can('settings.manage')<a href="{{ route('admin.settings.edit') }}">Website settings</a><a href="{{ route('admin.development') }}">Development</a>@endcan @can('leads.view')<a href="{{ route('admin.enquiries') }}">Enquiries</a>@endcan
@if(\App\Http\Middleware\RequireTwoFactor::enforced())<a href="{{ route('admin.security') }}">Account security</a>@endif <form method="post" action="{{ route('logout') }}">@csrf<button class="quiet">Sign out</button></form></nav>@endif @endauth
<main id="main">@if(session('status'))<p class="notice" role="status">{{ match(session('status')) { 'two-factor-authentication-enabled' => 'Scan the code below to finish setting up two-factor authentication.', 'two-factor-authentication-confirmed' => 'Two-factor authentication confirmed. You can now open the overview.', 'two-factor-authentication-disabled' => 'Two-factor authentication disabled.', 'recovery-codes-generated' => 'New recovery codes generated. Previous codes no longer work.', 'password-updated' => 'Your password was updated.', default => session('status') } }}</p>@endif
@if($errors->any())<div class="errors" role="alert"><strong>Please check the following:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@yield('content')</main><footer>Local development · {{ count(config('development.modules')) }} modules total · {{ config('development.completed') }} complete · {{ count(config('development.modules'))-config('development.completed') }} remaining</footer></body></html>
